### ISSUE TITLE
interpreter doesn't work :(

### ISSUE THREAD

**Issue by vihanb** [ETHproductions/cubix#2]
I went to run the hello world when I saw this: :disappointed: 

```
[Error] ReferenceError: Can't find variable: run
    onclick
```

pls fix asap

**Comment by ETHproductions** [comment]
I don't get this error running [version 0.3](https://jsfiddle.net/vvc4dgvq/6/). What browser are you using?

**Comment by vihanb** [comment]
Safari 9.0.1, OS X 10.11.1. Seems to go away when I refresh the page sometimes :confused:

**Comment by ETHproductions** [comment]
Do you still have this problem?
